image_tag: master-a995e3b5
image: public.ecr.aws/tensorleap/node-server
disableDatadogMetrics: false
enableKeycloak: true

ingress:
  enabled: true

mongodb:
  enabled: true
  connectionString: mongodb://mongodb/tensorleap?tls=false&ssl=false

mongodb_image: docker.io/library/mongo:6.0.5
