<<<<<<< HEAD
image_tag: master-fdaf4ea1
=======
image_tag: master-a995e3b5
>>>>>>> parent of ecf273b9 (Update image tags)
image: public.ecr.aws/tensorleap/node-server
disableDatadogMetrics: false
enableKeycloak: true

ingress:
  enabled: true

mongodb:
  enabled: true
  connectionString: mongodb://mongodb/tensorleap?tls=false&ssl=false

mongodb_image: docker.io/library/mongo:6.0.5
