apiVersion: v2
name: tensorleap-infra
type: application
version: 1.1.4
dependencies:
  - name: eck-operator
    repository: https://helm.elastic.co
    version: 2.8.0
    condition: eck-operator.enabled
