apiVersion: v2
name: tensorleap-infra
type: application
version: 1.1.5
dependencies:
  - name: eck-operator
    repository: https://helm.elastic.co
    version: 2.8.0
    condition: eck-operator.enabled
  - name: gpu-operator
    repository: https://helm.ngc.nvidia.com/nvidia
    version: v24.9.0
    condition: gpu-operator.enabled
