name: Release Production

on:
  workflow_dispatch:

# Allow pushing new branches using the provided token
permissions:
  contents: write

jobs:
  release-production:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Remove -rc.x suffix from chart versions
        run: make remove-rc-suffix
        shell: bash

      - name: Get chart version
        id: get_version
        run: |
          CHART_VERSION=$(grep -E '^version:' charts/tensorleap/Chart.yaml | awk '{print $2}')
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $CHART_VERSION"
        shell: bash

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Extract image names
        run: |
          make build-helm
          make update-images
        shell: bash

      # - name: Validate images.txt
      #   run: make validate-images
      #   shell: bash

      # - name: Helm Chart Validation (Tensorleap)
      #   uses: tensorleap/reusable-workflows/actions/helm-validate@master
      #   with:
      #     chart_path: './charts/tensorleap'

      # - name: Helm Chart Validation (Tensorleap Infra)
      #   uses: tensorleap/reusable-workflows/actions/helm-validate@master
      #   with:
      #     chart_path: './charts/tensorleap-infra'

      - name: Commit version changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Remove -rc.x suffix for production release and update images.txt"
          github_token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}

      - name: Release Charts
        uses: ./.github/actions/release-chart
        with:
          github_token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Release Manifest
        uses: ./.github/actions/release-manifest
        with:
          github_token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          custom_tag_prefix: "manifest"
          branch: ${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate Release Notes & Update Jira fixVersion
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_EMAIL: omri.yonatani@tensorleap.ai
          JIRA_DOMAIN: https://tensorleap.atlassian.net
          CREATE_FIX_VERSION: 'true'
          UPDATE_FIX_VERSION: 'true'
        run: make release-notes

      - name: Commit Release Notes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'RELEASE_NOTES.md'
          message: "docs: update release notes for v${{ steps.get_version.outputs.version }}"
          github_token: ${{ secrets.TENSORLEAP_OPS_GITHUB_TOKEN }}
          
      - name: Notify Slack - Release Complete
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage # https://api.slack.com/methods/chat.postMessage
          token: ${{ secrets.SLACK_TOKEN }}
          payload: |
            channel: "releases",
            text: "ðŸš€ *on-prem* version ${{ steps.get_version.outputs.version }} released by ${{ github.actor }} | View workflow --> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            

  release-airgap:
    name: Release Airgap Pack
    needs: release-production
    uses: ./.github/workflows/release_airgap_pack.yml
    with:
      manifest_name: manifest-${{ needs.release-production.outputs.version }}
    secrets: inherit

  install-server:
    needs: [release-production, release-airgap]
    uses: ./.github/workflows/_install_server.yml
    with:
      tag: manifest-${{ needs.release-production.outputs.version }}
